### ISSUE TITLE
update wet distro

### ISSUE THREAD

**Issue by jdearie** [Drupal4Gov/D4G-website#3]
lots of security and core updates since i first installed wetkit on the dev enviro. install 7.x-1.8 version of wetkit on dev and go from there.

**Comment by jdearie** [comment]
updated to 1.8 on dev

**Comment by timwood** [comment]
Hey @jdearie . Just noticed this via email notification. Do you think we should use the 4.0beta instead? I realize Acquia's "Install Drupal" feature doesn't offer the beta, but we could add the code manually.

**Comment by jdearie** [comment]
at this point, i just want to be able to get something into production introducing who we are. would love to have it live by march 17th.    i'm not sure the beta is ready for that yet... we can always upgrade later.
